# Generated by Django 4.1.1 on 2024-01-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicsAdvocacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
            options={
                'verbose_name_plural': 'Economics Advocacy',
            },
        ),
        migrations.CreateModel(
            name='Governance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
            options={
                'verbose_name_plural': 'Governance',
            },
        ),
        migrations.CreateModel(
            name='HealthAdvocacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
            options={
                'verbose_name_plural': 'Health Advocacy',
            },
        ),
        migrations.CreateModel(
            name='ParliamentaryMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
            options={
                'verbose_name_plural': 'Parliamentary Monitoring',
            },
        ),
        migrations.CreateModel(
            name='SocialAccountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
            options={
                'verbose_name_plural': 'Social Development',
            },
        ),
    ]
