# Generated by Django 4.1.1 on 2024-01-18 21:04

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Image')),
                ('rank', models.IntegerField(default=0, verbose_name='Rank')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
